name: 'Pulls a project spec and state'
description: 'Pulls a project spec and state Lightning instance'
inputs:
  secret_input:
    description: "OpenFN API KEY"
    required: true
  project_id_input:
    description: "OpenFN Project ID"
    required: true
  commit_message: 
    description: "Pull Commit Message"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Project export
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: |
        npm install -g @openfn/cli
        openfn pull $OPENFN_PROJECT_ID -c config.json --no-confirm
      shell: bash
      env: 
        OPENFN_API_KEY: ${{ inputs.secret_input }}
        OPENFN_PROJECT_ID: ${{ inputs.project_id_input }}
    - name: Commit new state file
      uses: stefanzweifel/git-auto-commit-action@v4
      env:
        OPENFN_COMMIT_MESSAGE: ${{ inputs.commit_message }}
      with: 
        commit_message: $OPENFN_COMMIT_MESSAGE

        
